// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// rtruncnorm
double rtruncnorm(double y, double mu, double sigma, int K);
RcppExport SEXP DPsurv_rtruncnorm(SEXP ySEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(rtruncnorm(y, mu, sigma, K));
    return __result;
END_RCPP
}
// vec2mat
NumericMatrix vec2mat(NumericVector x, int nb);
RcppExport SEXP DPsurv_vec2mat(SEXP xSEXP, SEXP nbSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nb(nbSEXP);
    __result = Rcpp::wrap(vec2mat(x, nb));
    return __result;
END_RCPP
}
// eStep
NumericMatrix eStep(NumericVector theta, NumericVector phi, NumericVector w, S4 DataStorage);
RcppExport SEXP DPsurv_eStep(SEXP thetaSEXP, SEXP phiSEXP, SEXP wSEXP, SEXP DataStorageSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< S4 >::type DataStorage(DataStorageSEXP);
    __result = Rcpp::wrap(eStep(theta, phi, w, DataStorage));
    return __result;
END_RCPP
}
// mStep
S4 mStep(S4 DP, S4 DataStorage, IntegerVector xi, IntegerVector zeta);
RcppExport SEXP DPsurv_mStep(SEXP DPSEXP, SEXP DataStorageSEXP, SEXP xiSEXP, SEXP zetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type DP(DPSEXP);
    Rcpp::traits::input_parameter< S4 >::type DataStorage(DataStorageSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type zeta(zetaSEXP);
    __result = Rcpp::wrap(mStep(DP, DataStorage, xi, zeta));
    return __result;
END_RCPP
}
// gibbsStep
S4 gibbsStep(S4 DP, S4 DataStorage, NumericVector RealData, IntegerVector xi, IntegerVector zeta, IntegerVector censoring);
RcppExport SEXP DPsurv_gibbsStep(SEXP DPSEXP, SEXP DataStorageSEXP, SEXP RealDataSEXP, SEXP xiSEXP, SEXP zetaSEXP, SEXP censoringSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type DP(DPSEXP);
    Rcpp::traits::input_parameter< S4 >::type DataStorage(DataStorageSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type RealData(RealDataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type zeta(zetaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type censoring(censoringSEXP);
    __result = Rcpp::wrap(gibbsStep(DP, DataStorage, RealData, xi, zeta, censoring));
    return __result;
END_RCPP
}
