# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rtruncnorm <- function(y, mu, sigma, K = 1L) {
    .Call('DPsurv_rtruncnorm', PACKAGE = 'DPsurv', y, mu, sigma, K)
}

vec2mat <- function(x, nb) {
    .Call('DPsurv_vec2mat', PACKAGE = 'DPsurv', x, nb)
}

eStep <- function(theta, phi, w, DataStorage) {
    .Call('DPsurv_eStep', PACKAGE = 'DPsurv', theta, phi, w, DataStorage)
}

mStep <- function(DP, DataStorage, xi, zeta) {
    .Call('DPsurv_mStep', PACKAGE = 'DPsurv', DP, DataStorage, xi, zeta)
}

gibbsStep <- function(DP, DataStorage, RealData, xi, zeta, censoring) {
    .Call('DPsurv_gibbsStep', PACKAGE = 'DPsurv', DP, DataStorage, RealData, xi, zeta, censoring)
}

